FROM fluent/fluentd:latest
MAINTAINER Everydayhero <edh-dev@everydayhero.com.au>

RUN apk --no-cache --update add ruby-io-console build-base ruby-dev

RUN gem install \
    fluent-plugin-docker_metadata_filter \
    fluent-plugin-kinesis \
    bundler \
    --no-rdoc --no-ri

EXPOSE 5140
EXPOSE 5170
EXPOSE 24224

RUN mkdir -p /tmp/rspec
WORKDIR /tmp/rspec
ADD . /tmp/rspec

RUN bundle install

CMD ["rspec"]
