---
env:
  DOCKER_REPO: quay.io/everydayhero/fluentd

steps:
  - wait

  - name: ":docker: :checkered_flag:"
    command: "docker build -t \"${DOCKER_REPO}:${BUILDKITE_COMMIT}\" && docker push \"${DOCKER_REPO}:${BUILDKITE_COMMIT}\""

  - wait

  - name: ':rspec:'
    command: 'rspec --color'
    env:
      BUILDKITE_DOCKER: true

  - wait

  - name: ":docker: :rocket:"
    command: "docker tag -f \"${DOCKER_REPO}:${BUILDKITE_COMMIT}\" \"${DOCKER_REPO}:${DOCKER_TAG}\""
    env:
      DOCKER_TAG: testing
