---
steps:
  - name: ":rspec:"
    command: "bin/ci"

  - wait

  - name: ":docker: Build Image"
    command: bin/build

  - wait

  - name: ":docker: Tag Staging"
    command: bin/tag staging
    branches: master

  - wait

  - name: ":ansible: Deploy"
    command: "plain-utils ansible-playbook $ENVIRONMENT master bootstrap.yml --tags fluentd"
    branches: master
    env:
      ENVIRONMENT: staging

  - block

  - name: ":docker: Tag Production"
    command: bin/tag production
    branches: master

  - wait

  - name: ":ansible: Deploy"
    command: "plain-utils ansible-playbook $ENVIRONMENT master bootstrap.yml --tags fluentd"
    branches: master
    env:
      ENVIRONMENT: production
