# buildkite.yml

steps:
  -
    type: "waiter"

  -
    name: "Run rspec"
    command: "bin/ci"
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Build docker image (staging)"
    command: "docker build -t \"quay.io/everydayhero/fluentd:staging\" ."
    branches: "master"
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Push new build"
    command: "docker push quay.io/everydayhero/fluentd:staging"
    branches: "master"
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Deploy to staging"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l \\!rabbitmq,\\!consul-server,\\!kibana --tags fluentd coreos.yml"
    branches: "master"
    parallelism: 1
    concurrency: 1
    concurrency_group: deploy-staging
    env:
      ENVIRONMENT: "staging"
    agents:
      - "plain_utils=true"

  -
    type: "manual"

  -
    name: "Build docker image (production)"
    command: "docker build -t \"quay.io/everydayhero/fluentd:production\" ."
    branches: "master"
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Push new build"
    command: "docker push quay.io/everydayhero/fluentd:production"
    branches: "master"
    agents:
      - "plain_utils=true"
