---
steps:
  - name: ":rspec:"
    command: "bin/ci"
    agents:
      queue: "*"

  - type: waiter

  - name: ":docker: Build Image"
    command: bin/build
    agents:
      queue: "*"
      docker: builder

  - type: waiter

  - name: ":docker: Tag Staging"
    command: bin/tag staging
    branches: master
    agents:
      queue: "*"
      docker: builder

  - type: manual

  - name: ":ansible: Deploy"
    command: "plain-utils ansible-playbook $ENVIRONMENT master bootstrap.yml --tags fluentd"
    branches: master
    env:
      ENVIRONMENT: staging
    agents:
      queue: "*"

  - type: manual

  - name: ":docker: Tag Production"
    command: bin/tag production
    branches: master
    agents:
      queue: "*"
      docker: builder

  - type: waiter

  - name: ":ansible: Deploy"
    command: "plain-utils ansible-playbook $ENVIRONMENT master bootstrap.yml --tags fluentd"
    branches: master
    env:
      ENVIRONMENT: production
    agents:
      queue: "*"
